import React from "react";

export type ContactFormEmailProps = {
  message: string;
  senderEmail: string;
  senderName: string;
  ip?: string;
  extra?: string;
};

export default function ContactFormEmail({
  message,
  senderEmail,
  senderName,
  ip = "unknown",
  extra = "",
}: ContactFormEmailProps) {
  // Inline styles so the rendered HTML is self-contained (no external CSS required)
  const outer: React.CSSProperties = {
    fontFamily: 'Helvetica, Arial, sans-serif',
    backgroundColor: '#f6f7fb',
    color: '#111827',
    padding: '24px',
  };

  const card: React.CSSProperties = {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: '20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  };

  const heading: React.CSSProperties = {
    fontSize: 18,
    fontWeight: 700,
    margin: '0 0 12px 0',
    color: '#0f172a',
  };

  const text: React.CSSProperties = {
    fontSize: 14,
    margin: '8px 0',
    whiteSpace: 'pre-wrap', // preserves line breaks from the message
  };

  const metaLabel: React.CSSProperties = { fontWeight: 600, marginRight: 6 };

  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>New message from your portfolio</title>
      </head>
      <body style={outer as any}>
        <div style={card}>
          <h1 style={heading}>You received a new message from your portfolio contact form</h1>

          <div style={text}>
            {message || '(no message)'}
          </div>

          <hr />

          <div style={{ marginTop: 12 }}>
            <div style={text}>
              <span style={metaLabel}>From:</span>
              {senderName || 'Unknown'}
            </div>

            <div style={text}>
              <span style={metaLabel}>Email:</span>
              {senderEmail || 'Unknown'}
            </div>

            <div style={text}>
              <span style={metaLabel}>IP:</span>
              {ip}
            </div>

            {extra ? (
              <div style={text}>
                <span style={metaLabel}>Extra:</span>
                {extra}
              </div>
            ) : null}
          </div>

          <p style={{ fontSize: 12, color: '#6b7280', marginTop: 18 }}>
            This email was generated by your portfolio contact form.
          </p>
        </div>
      </body>
    </html>
  );
}
